#!/usr/bin/env bash
# stub-engine.sh
#
# Generates no-op TypeScript stubs for the formula-engine submodule.
#
# The formula engine lives in src/lib/engine/ and is built from Rust into
# a WASM binary (pkg/formula_engine.js + .wasm).  That binary is not
# compiled during CI because the Rust toolchain is not installed on the
# runner.  Without stubs, TypeScript cannot resolve the imports from
# bridge.ts and bridgeTypes.ts, and both tsc and eslint fail.
#
# This script creates two files:
#   - bridgeTypes.ts  — interfaces and helper functions
#   - bridge.ts       — re-exports types and provides no-op implementations
#
# Every exported symbol matches the real source so downstream imports
# compile without modification.
#
# Called automatically by the CI workflow:
#   if [ ! -f src/lib/engine/pkg/formula_engine.js ]; then
#     bash .github/scripts/stub-engine.sh
#   fi
set -euo pipefail

DIR="src/lib/engine"
mkdir -p "$DIR"

# ── bridgeTypes.ts ────────────────────────────────────────────────────────────
cat > "$DIR/bridgeTypes.ts" << 'STUB'
// CI STUB — auto-generated by .github/scripts/stub-engine.sh

export interface FormulaValue {
  type: 'number' | 'text' | 'boolean' | 'date' | 'dateRange' | 'array' | 'empty';
  value?: unknown;
}

export interface CompileResult {
  ok: boolean;
  handle?: number;
  error?: string;
  error_pos?: [number, number];
}

export interface EvalResult {
  ok: boolean;
  value?: FormulaValue;
  error?: string;
}

export interface BatchResult {
  ok: boolean;
  values?: FormulaValue[];
  error?: string;
}

export interface ValidateResult {
  ok: boolean;
  errors: Array<{ message: string; start: number; end: number }>;
  dependencies: string[];
}

export type PropertyMap = Record<string, unknown>;

export function toJsonValue(val: unknown): FormulaValue {
  if (val === null || val === undefined) return { type: 'empty' };
  if (typeof val === 'number') return { type: 'number', value: val };
  if (typeof val === 'string') return { type: 'text', value: val };
  if (typeof val === 'boolean') return { type: 'boolean', value: val };
  if (val instanceof Date) return { type: 'date', value: val.getTime() };
  if (Array.isArray(val)) return { type: 'array', value: val.map(toJsonValue) };
  return { type: 'text', value: String(val) };
}

export function fromFormulaValue(fv: FormulaValue | undefined): unknown {
  if (!fv || fv.type === 'empty') return '';
  return fv.value ?? '';
}

export function propsToJson(props: PropertyMap): string {
  return JSON.stringify(props);
}
STUB

# ── bridge.ts ─────────────────────────────────────────────────────────────────
cat > "$DIR/bridge.ts" << 'STUB'
// CI STUB — auto-generated by .github/scripts/stub-engine.sh
import type { CompileResult, ValidateResult, PropertyMap } from './bridgeTypes';
export type {
  FormulaValue, CompileResult, EvalResult, BatchResult,
  ValidateResult, PropertyMap,
} from './bridgeTypes';

export async function initFormulaEngine(): Promise<boolean> { return false; }
export function isWasmReady(): boolean { return false; }
export function compileFormula(_formula: string): CompileResult | null { return null; }
export function evalFormula(_formula: string, _props: PropertyMap): unknown { return ''; }
export function evaluateHandle(_handle: number, _props: PropertyMap): unknown { return ''; }
export function batchEvaluate(_formula: string, rows: PropertyMap[]): unknown[] { return rows.map(() => ''); }
export function validateFormula(_formula: string): ValidateResult {
  return { ok: true, errors: [], dependencies: [] };
}
export function getDependencies(_handle: number): string[] { return []; }
export function freeFormula(_handle: number): void {}
export function clearFormulaCache(): void {}
STUB

echo "✓ Engine bridge stubs created in $DIR"
