#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# stub-engine.sh — generate no-op stubs for the formula-engine submodule
#
# Called by CI when the private src/lib/engine submodule cannot be checked out.
# The stubs export the same public API as the real bridge so TypeScript
# type-checking and ESLint pass without the WASM binary.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DIR="src/lib/engine"
mkdir -p "$DIR"

# ── bridgeTypes.ts ────────────────────────────────────────────────────────────
cat > "$DIR/bridgeTypes.ts" << 'STUB'
// CI STUB — auto-generated by .github/scripts/stub-engine.sh

export interface FormulaValue {
  type: 'number' | 'text' | 'boolean' | 'date' | 'dateRange' | 'array' | 'empty';
  value?: unknown;
}

export interface CompileResult {
  ok: boolean;
  handle?: number;
  error?: string;
  error_pos?: [number, number];
}

export interface EvalResult {
  ok: boolean;
  value?: FormulaValue;
  error?: string;
}

export interface BatchResult {
  ok: boolean;
  values?: FormulaValue[];
  error?: string;
}

export interface ValidateResult {
  ok: boolean;
  errors: Array<{ message: string; start: number; end: number }>;
  dependencies: string[];
}

export type PropertyMap = Record<string, unknown>;

export function toJsonValue(val: unknown): FormulaValue {
  if (val === null || val === undefined) return { type: 'empty' };
  if (typeof val === 'number') return { type: 'number', value: val };
  if (typeof val === 'string') return { type: 'text', value: val };
  if (typeof val === 'boolean') return { type: 'boolean', value: val };
  if (val instanceof Date) return { type: 'date', value: val.getTime() };
  if (Array.isArray(val)) return { type: 'array', value: val.map(toJsonValue) };
  return { type: 'text', value: String(val) };
}

export function fromFormulaValue(fv: FormulaValue | undefined): unknown {
  if (!fv || fv.type === 'empty') return '';
  return fv.value ?? '';
}

export function propsToJson(props: PropertyMap): string {
  return JSON.stringify(props);
}
STUB

# ── bridge.ts ─────────────────────────────────────────────────────────────────
cat > "$DIR/bridge.ts" << 'STUB'
// CI STUB — auto-generated by .github/scripts/stub-engine.sh
import type { CompileResult, ValidateResult, PropertyMap } from './bridgeTypes';
export type {
  FormulaValue, CompileResult, EvalResult, BatchResult,
  ValidateResult, PropertyMap,
} from './bridgeTypes';

export async function initFormulaEngine(): Promise<boolean> { return false; }
export function isWasmReady(): boolean { return false; }
export function compileFormula(_formula: string): CompileResult | null { return null; }
export function evalFormula(_formula: string, _props: PropertyMap): unknown { return ''; }
export function evaluateHandle(_handle: number, _props: PropertyMap): unknown { return ''; }
export function batchEvaluate(_formula: string, rows: PropertyMap[]): unknown[] { return rows.map(() => ''); }
export function validateFormula(_formula: string): ValidateResult {
  return { ok: true, errors: [], dependencies: [] };
}
export function getDependencies(_handle: number): string[] { return []; }
export function freeFormula(_handle: number): void {}
export function clearFormulaCache(): void {}
STUB

echo "✓ Engine bridge stubs created in $DIR"
