#!/usr/bin/env bash
# scripts/audit-summary.sh
#
# Pretty-print the full audit summary after all 4 stages complete.
# Reads the step exit-codes (passed as args) and sonarcloud-issues.json
# to produce a rich, user-friendly terminal report.
#
# Usage:
#   bash scripts/audit-summary.sh <err_type> <err_lint> <err_sonar>
#
# Expects:
#   sonarcloud-issues.json   in the project root (generated by fetch-sonar-issues.py)
#   audit-typecheck.log      tsc output
#   audit-lint.log           eslint output
#   audit-sonar.log          sonar scanner output
set -uo pipefail
cd "$(dirname "$0")/.."

# ── Args ──────────────────────────────────────────────────────────────────────
ERR_TYPE="${1:-0}"
ERR_LINT="${2:-0}"
ERR_SONAR="${3:-0}"

# ── Colors & glyphs ──────────────────────────────────────────────────────────
R='\033[0;31m'     # red
G='\033[0;32m'     # green
Y='\033[0;33m'     # yellow/amber
B='\033[0;34m'     # blue
C='\033[0;36m'     # cyan
M='\033[0;35m'     # magenta
W='\033[1;37m'     # bold white
DIM='\033[2m'      # dim
BOLD='\033[1m'     # bold
RST='\033[0m'      # reset

PASS="${G}✔${RST}"
FAIL="${R}✘${RST}"
WARN="${Y}▲${RST}"
DOT="${DIM}·${RST}"
BAR_FULL="█"
BAR_EMPTY="░"

# ── Helpers ───────────────────────────────────────────────────────────────────
W_COL=60  # usable width for the report body
SEP_CHAR="─"
THICK_CHAR="═"

repeat_char() {
  local c="$1" n="$2" i
  for (( i=0; i<n; i++ )); do printf '%s' "$c"; done
}

sep()       { echo -e "${DIM}$(repeat_char "$SEP_CHAR" "$W_COL")${RST}"; }
thick_sep() { echo -e "${C}$(repeat_char "$THICK_CHAR" "$W_COL")${RST}"; }

header() {
  local title="$1"
  local pad=$(( (W_COL - ${#title} - 2) / 2 ))
  echo ""
  thick_sep
  printf "${C}%*s %s %*s${RST}\n" "$pad" "" "$title" "$pad" ""
  thick_sep
}

section() {
  local icon="$1" title="$2"
  echo ""
  echo -e "  ${BOLD}${icon}  ${title}${RST}"
  sep
}

status_line() {
  local label="$1" value="$2" color="${3:-$RST}"
  printf "  %-28s ${color}%s${RST}\n" "$label" "$value"
}

bar_chart() {
  # bar_chart <label> <count> <max> <color>
  local label="$1" count="$2" max="$3" color="$4"
  local bar_width=20
  local filled=0
  if [ "$max" -gt 0 ]; then
    filled=$(( count * bar_width / max ))
  fi
  [ "$filled" -gt "$bar_width" ] && filled=$bar_width
  local empty=$(( bar_width - filled ))
  printf "  %-14s %3d  ${color}%s${DIM}%s${RST}\n" \
    "$label" "$count" \
    "$(repeat_char "$BAR_FULL" "$filled")" \
    "$(repeat_char "$BAR_EMPTY" "$empty")"
}

# ── Count errors from logs ───────────────────────────────────────────────────
TSC_ERRORS=0
if [ "$ERR_TYPE" -ne 0 ] && [ -f audit-typecheck.log ]; then
  TSC_ERRORS=$(grep -c "error TS" audit-typecheck.log 2>/dev/null || echo 0)
fi

LINT_ERRORS=0
LINT_WARNINGS=0
if [ "$ERR_LINT" -ne 0 ] && [ -f audit-lint.log ]; then
  # ESLint prints "X errors and Y warnings" or "X problems (Y errors, Z warnings)"
  LINT_ERRORS=$(grep -oP '\d+(?= error)' audit-lint.log 2>/dev/null | tail -1 || echo 0)
  LINT_WARNINGS=$(grep -oP '\d+(?= warning)' audit-lint.log 2>/dev/null | tail -1 || echo 0)
  [ -z "$LINT_ERRORS" ] && LINT_ERRORS=0
  [ -z "$LINT_WARNINGS" ] && LINT_WARNINGS=0
fi

# ── Parse SonarQube JSON ─────────────────────────────────────────────────────
SONAR_FILE="sonarcloud-issues.json"
HAS_SONAR=false
SONAR_TOTAL=0
SONAR_BLOCKER=0
SONAR_CRITICAL=0
SONAR_MAJOR=0
SONAR_MINOR=0
SONAR_INFO=0
SONAR_BUGS=0
SONAR_VULNS=0
SONAR_SMELLS=0
SONAR_HOTSPOTS=0

if [ -f "$SONAR_FILE" ] && command -v python3 >/dev/null 2>&1; then
  HAS_SONAR=true
  eval "$(python3 -c "
import json, sys
with open('$SONAR_FILE') as f:
    d = json.load(f)
issues = d.get('issues', [])
total = len(issues)
sev = {}
typ = {}
for i in issues:
    s = i.get('severity', 'INFO')
    t = i.get('type', 'CODE_SMELL')
    sev[s] = sev.get(s, 0) + 1
    typ[t] = typ.get(t, 0) + 1
print(f'SONAR_TOTAL={total}')
print(f'SONAR_BLOCKER={sev.get(\"BLOCKER\", 0)}')
print(f'SONAR_CRITICAL={sev.get(\"CRITICAL\", 0)}')
print(f'SONAR_MAJOR={sev.get(\"MAJOR\", 0)}')
print(f'SONAR_MINOR={sev.get(\"MINOR\", 0)}')
print(f'SONAR_INFO={sev.get(\"INFO\", 0)}')
print(f'SONAR_BUGS={typ.get(\"BUG\", 0)}')
print(f'SONAR_VULNS={typ.get(\"VULNERABILITY\", 0)}')
print(f'SONAR_SMELLS={typ.get(\"CODE_SMELL\", 0)}')
print(f'SONAR_HOTSPOTS={typ.get(\"SECURITY_HOTSPOT\", 0)}')
" 2>/dev/null)"
fi

# ── Compute totals ───────────────────────────────────────────────────────────
TOTAL_ISSUES=$(( TSC_ERRORS + LINT_ERRORS + SONAR_TOTAL ))
ALL_OK=true
[ "$ERR_TYPE" -ne 0 ] || [ "$ERR_LINT" -ne 0 ] || [ "$ERR_SONAR" -ne 0 ] && ALL_OK=false
[ "$SONAR_TOTAL" -gt 0 ] && ALL_OK=false

# ═══════════════════════════════════════════════════════════════════════════════
#                            RENDER THE REPORT
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo ""
if $ALL_OK; then
  header "AUDIT REPORT — ALL CLEAR"
else
  header "AUDIT REPORT"
fi

# ── 1. Step Results ──────────────────────────────────────────────────────────
section "📋" "Step Results"
if [ "$ERR_TYPE" -eq 0 ]; then
  echo -e "  ${PASS}  ${BOLD}TypeScript${RST}        No type errors"
else
  echo -e "  ${FAIL}  ${BOLD}TypeScript${RST}        ${R}${TSC_ERRORS} type error(s)${RST}"
fi

if [ "$ERR_LINT" -eq 0 ]; then
  echo -e "  ${PASS}  ${BOLD}ESLint${RST}            No lint issues"
else
  echo -e "  ${FAIL}  ${BOLD}ESLint${RST}            ${R}${LINT_ERRORS} error(s)${RST}, ${Y}${LINT_WARNINGS} warning(s)${RST}"
fi

if [ "$ERR_SONAR" -eq 0 ]; then
  echo -e "  ${PASS}  ${BOLD}SonarQube Scan${RST}    Analysis uploaded successfully"
else
  echo -e "  ${FAIL}  ${BOLD}SonarQube Scan${RST}    ${R}Scanner failed${RST}"
fi

echo -e "  ${DOT}"
echo -e "  ${DIM}Logs: audit-typecheck.log · audit-lint.log · audit-sonar.log${RST}"

# ── 2. SonarQube Issues ─────────────────────────────────────────────────────
if $HAS_SONAR; then
  section "🔍" "SonarQube Issues  (${SONAR_TOTAL} total)"

  if [ "$SONAR_TOTAL" -eq 0 ]; then
    echo -e "  ${G}No issues found — great job!${RST}"
  else
    # Severity breakdown with colored bars
    MAX_SEV=$SONAR_TOTAL
    echo -e "  ${DIM}By Severity${RST}"
    [ "$SONAR_BLOCKER"  -gt 0 ] && bar_chart "Blocker"  "$SONAR_BLOCKER"  "$MAX_SEV" "$R"
    [ "$SONAR_CRITICAL" -gt 0 ] && bar_chart "Critical" "$SONAR_CRITICAL" "$MAX_SEV" "$R"
    [ "$SONAR_MAJOR"    -gt 0 ] && bar_chart "Major"    "$SONAR_MAJOR"    "$MAX_SEV" "$Y"
    [ "$SONAR_MINOR"    -gt 0 ] && bar_chart "Minor"    "$SONAR_MINOR"    "$MAX_SEV" "$C"
    [ "$SONAR_INFO"     -gt 0 ] && bar_chart "Info"     "$SONAR_INFO"     "$MAX_SEV" "$DIM"

    echo ""
    echo -e "  ${DIM}By Type${RST}"
    [ "$SONAR_SMELLS"   -gt 0 ] && bar_chart "Code Smell"   "$SONAR_SMELLS"   "$MAX_SEV" "$Y"
    [ "$SONAR_BUGS"     -gt 0 ] && bar_chart "Bug"          "$SONAR_BUGS"     "$MAX_SEV" "$R"
    [ "$SONAR_VULNS"    -gt 0 ] && bar_chart "Vulnerability" "$SONAR_VULNS"   "$MAX_SEV" "$R"
    [ "$SONAR_HOTSPOTS" -gt 0 ] && bar_chart "Hotspot"      "$SONAR_HOTSPOTS" "$MAX_SEV" "$M"

    # Top affected files
    echo ""
    echo -e "  ${DIM}Top Affected Files${RST}"
    python3 -c "
import json
with open('$SONAR_FILE') as f:
    d = json.load(f)
files = {}
for i in d.get('issues', []):
    comp = i.get('component', '').split(':')[-1]
    files[comp] = files.get(comp, 0) + 1
ranked = sorted(files.items(), key=lambda x: -x[1])[:8]
for path, count in ranked:
    # Truncate long paths from the left
    display = path
    if len(display) > 42:
        display = '…' + display[-41:]
    sev_map = {}
    for i in d.get('issues', []):
        if i.get('component', '').endswith(path):
            s = i.get('severity', 'INFO')
            sev_map[s] = sev_map.get(s, 0) + 1
    parts = []
    for s in ['BLOCKER','CRITICAL','MAJOR','MINOR','INFO']:
        if s in sev_map:
            parts.append(f'{sev_map[s]}{s[0]}')
    detail = ' '.join(parts)
    print(f'  {count:3d}  {display:44s} {detail}')
" 2>/dev/null

    # Individual issues list (compact)
    echo ""
    sep
    echo -e "  ${DIM}Issue Details${RST}"
    echo ""
    python3 -c "
import json

SEV_ICON = {
    'BLOCKER':  '\033[0;31m■\033[0m',
    'CRITICAL': '\033[0;31m▪\033[0m',
    'MAJOR':    '\033[0;33m▪\033[0m',
    'MINOR':    '\033[0;36m▫\033[0m',
    'INFO':     '\033[2m▫\033[0m'
}
SEV_ORDER = {'BLOCKER': 0, 'CRITICAL': 1, 'MAJOR': 2, 'MINOR': 3, 'INFO': 4}

with open('$SONAR_FILE') as f:
    d = json.load(f)
issues = d.get('issues', [])
issues.sort(key=lambda i: (
    SEV_ORDER.get(i.get('severity', 'INFO'), 5),
    i.get('component', ''),
    i.get('line', 0),
))
for idx, issue in enumerate(issues, 1):
    sev = issue.get('severity', 'INFO')
    icon = SEV_ICON.get(sev, '·')
    comp = issue.get('component', '').split(':')[-1]
    line = issue.get('line', '-')
    msg  = issue.get('message', '')
    rule = issue.get('rule', '').split(':')[-1]
    effort = issue.get('effort', '')

    # Truncate path
    if len(comp) > 46:
        comp = '…' + comp[-45:]

    # Truncate message
    if len(msg) > 52:
        msg = msg[:49] + '…'

    print(f'  {icon} {sev:8s}  {comp}:{line}')
    print(f'             \033[2m{rule}\033[0m  {msg}')
    if effort:
        print(f'             \033[2mEffort: {effort}\033[0m')
    print()
" 2>/dev/null
  fi

  echo -e "  ${DIM}Full report: sonarcloud-report.txt${RST}"
  echo -e "  ${DIM}Raw data:    sonarcloud-issues.json${RST}"
fi

# ── 3. TypeScript Errors (if any) ───────────────────────────────────────────
if [ "$ERR_TYPE" -ne 0 ] && [ -f audit-typecheck.log ] && [ "$TSC_ERRORS" -gt 0 ]; then
  section "🔴" "TypeScript Errors  (${TSC_ERRORS})"
  grep "error TS" audit-typecheck.log 2>/dev/null | head -15 | while IFS= read -r line; do
    # Strip path prefix
    clean=$(echo "$line" | sed "s|$(pwd)/||")
    echo -e "  ${R}→${RST} ${clean}"
  done
  if [ "$TSC_ERRORS" -gt 15 ]; then
    echo -e "  ${DIM}… and $(( TSC_ERRORS - 15 )) more (see audit-typecheck.log)${RST}"
  fi
fi

# ── 4. ESLint Errors (if any) ───────────────────────────────────────────────
if [ "$ERR_LINT" -ne 0 ] && [ -f audit-lint.log ]; then
  section "🟡" "ESLint Issues"
  # Print the first chunk of relevant output
  grep -E "error|warning" audit-lint.log 2>/dev/null | head -15 | while IFS= read -r line; do
    clean=$(echo "$line" | sed "s|$(pwd)/||")
    echo -e "  ${Y}→${RST} ${clean}"
  done
  echo -e "  ${DIM}(see audit-lint.log for full output)${RST}"
fi

# ── 5. Grand Total ──────────────────────────────────────────────────────────
section "📊" "Grand Total"

status_line "TypeScript errors:"  "$TSC_ERRORS"      "$([ "$TSC_ERRORS" -gt 0 ]   && echo "$R" || echo "$G")"
status_line "ESLint errors:"      "$LINT_ERRORS"      "$([ "$LINT_ERRORS" -gt 0 ]  && echo "$R" || echo "$G")"
status_line "ESLint warnings:"    "$LINT_WARNINGS"    "$([ "$LINT_WARNINGS" -gt 0 ] && echo "$Y" || echo "$G")"
status_line "SonarQube issues:"   "$SONAR_TOTAL"      "$([ "$SONAR_TOTAL" -gt 0 ]  && echo "$Y" || echo "$G")"
sep
printf "  ${BOLD}%-28s${RST} " "Total:"
if [ "$TOTAL_ISSUES" -eq 0 ]; then
  echo -e "${G}${BOLD}0${RST}"
else
  echo -e "${Y}${BOLD}${TOTAL_ISSUES} issue(s)${RST}"
fi

# ── 6. Final Verdict ────────────────────────────────────────────────────────
echo ""
if $ALL_OK; then
  echo -e "  ${G}╭──────────────────────────────────────────────╮${RST}"
  echo -e "  ${G}│                                              │${RST}"
  echo -e "  ${G}│     ✔  ALL CHECKS PASSED — SHIP IT! 🚀      │${RST}"
  echo -e "  ${G}│                                              │${RST}"
  echo -e "  ${G}╰──────────────────────────────────────────────╯${RST}"
elif [ "$ERR_TYPE" -ne 0 ] || [ "$ERR_LINT" -ne 0 ] || [ "$ERR_SONAR" -ne 0 ]; then
  echo -e "  ${R}╭──────────────────────────────────────────────╮${RST}"
  echo -e "  ${R}│                                              │${RST}"
  echo -e "  ${R}│     ✘  AUDIT FAILED — FIX BEFORE PUSHING    │${RST}"
  echo -e "  ${R}│                                              │${RST}"
  echo -e "  ${R}╰──────────────────────────────────────────────╯${RST}"
  exit 1
else
  echo -e "  ${Y}╭──────────────────────────────────────────────╮${RST}"
  echo -e "  ${Y}│                                              │${RST}"
  echo -e "  ${Y}│   ▲  AUDIT PASSED WITH WARNINGS — REVIEW     │${RST}"
  echo -e "  ${Y}│                                              │${RST}"
  echo -e "  ${Y}╰──────────────────────────────────────────────╯${RST}"
fi
echo ""
