/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   coreSeedData.ts                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/04/02 14:39:27 by dlesieur          #+#    #+#             */
/*   Updated: 2026/04/02 14:48:56 by dlesieur         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

// coreSeed — pages and views for Tasks, CRM, Content & Inventory
import type { Page, ViewConfig } from '../../../types/database';

// Inline constants to avoid circular dependency with coreSeed.ts
const DB_TASKS = 'db-tasks';
const DB_CRM = 'db-crm';
const DB_CONTENT = 'db-content';
const DB_INVENTORY = 'db-inventory';

function daysFromNow(offset: number): string {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return date.toISOString();
}

const now = new Date().toISOString();
const d = daysFromNow;

export const corePages: Record<string, Page> = {
  // — Tasks —
  't1': { id: 't1', databaseId: DB_TASKS, icon: '🎨', properties: { 'prop-title': 'Design Database Schema', 'prop-status': 'opt-done', 'prop-priority': 'pri-high', 'prop-tags': ['tag-design'], 'prop-assignee': 'Alice', 'prop-due': d(-4), 'prop-done': true, 'prop-points': 5, 'prop-task-id': 'TASK-1' }, content: [{ id: 'b1', type: 'paragraph', content: 'Define the core data structures for the database system.' }], createdAt: d(-10), updatedAt: d(-1), createdBy: 'Alice', lastEditedBy: 'Alice' },
  't2': { id: 't2', databaseId: DB_TASKS, icon: '⚙️', properties: { 'prop-title': 'Implement View Engine', 'prop-status': 'opt-in-progress', 'prop-priority': 'pri-urgent', 'prop-tags': ['tag-feature'], 'prop-assignee': 'Bob', 'prop-due': d(2), 'prop-done': false, 'prop-points': 13, 'prop-task-id': 'TASK-2' }, content: [{ id: 'b2', type: 'paragraph', content: 'Build the core view engine that powers table, board, calendar, timeline, gallery, list views.' }], createdAt: d(-7), updatedAt: now, createdBy: 'Bob', lastEditedBy: 'Bob' },
  't3': { id: 't3', databaseId: DB_TASKS, icon: '🐛', properties: { 'prop-title': 'Fix Drag-and-Drop Bug', 'prop-status': 'opt-todo', 'prop-priority': 'pri-med', 'prop-tags': ['tag-bug'], 'prop-assignee': 'Charlie', 'prop-due': d(5), 'prop-done': false, 'prop-points': 3, 'prop-task-id': 'TASK-3' }, content: [], createdAt: d(-3), updatedAt: d(-3), createdBy: 'Charlie', lastEditedBy: 'Charlie' },
  't4': { id: 't4', databaseId: DB_TASKS, icon: '📖', properties: { 'prop-title': 'Write API Documentation', 'prop-status': 'opt-todo', 'prop-priority': 'pri-low', 'prop-tags': ['tag-docs'], 'prop-assignee': 'Alice', 'prop-due': d(10), 'prop-done': false, 'prop-points': 2, 'prop-task-id': 'TASK-4' }, content: [], createdAt: d(-2), updatedAt: d(-2), createdBy: 'Alice', lastEditedBy: 'Alice' },
  't5': { id: 't5', databaseId: DB_TASKS, icon: '🚀', properties: { 'prop-title': 'Deploy to Production', 'prop-status': 'opt-blocked', 'prop-priority': 'pri-high', 'prop-tags': ['tag-infra'], 'prop-assignee': 'Bob', 'prop-due': d(7), 'prop-done': false, 'prop-points': 8, 'prop-task-id': 'TASK-5' }, content: [], createdAt: d(-1), updatedAt: d(-1), createdBy: 'Bob', lastEditedBy: 'Bob' },
  't6': { id: 't6', databaseId: DB_TASKS, icon: '🧪', properties: { 'prop-title': 'Write Integration Tests', 'prop-status': 'opt-review', 'prop-priority': 'pri-med', 'prop-tags': ['tag-feature', 'tag-infra'], 'prop-assignee': 'Diana', 'prop-due': d(3), 'prop-done': false, 'prop-points': 5, 'prop-task-id': 'TASK-6' }, content: [], createdAt: d(-5), updatedAt: now, createdBy: 'Diana', lastEditedBy: 'Diana' },
  't7': { id: 't7', databaseId: DB_TASKS, icon: '🎯', properties: { 'prop-title': 'Performance Optimization', 'prop-status': 'opt-in-progress', 'prop-priority': 'pri-high', 'prop-tags': ['tag-infra'], 'prop-assignee': 'Eve', 'prop-due': d(4), 'prop-done': false, 'prop-points': 8, 'prop-task-id': 'TASK-7' }, content: [], createdAt: d(-4), updatedAt: now, createdBy: 'Eve', lastEditedBy: 'Eve' },
  't8': { id: 't8', databaseId: DB_TASKS, icon: '💅', properties: { 'prop-title': 'UI Polish Pass', 'prop-status': 'opt-todo', 'prop-priority': 'pri-med', 'prop-tags': ['tag-design'], 'prop-assignee': 'Alice', 'prop-due': d(8), 'prop-done': false, 'prop-points': 3, 'prop-task-id': 'TASK-8' }, content: [], createdAt: d(-1), updatedAt: d(-1), createdBy: 'Alice', lastEditedBy: 'Alice' },
  // — CRM —
  'c1': { id: 'c1', databaseId: DB_CRM, icon: '🏢', properties: { 'prop-name': 'Acme Corporation', 'prop-company': 'Acme Inc', 'prop-stage': 'crm-customer', 'prop-value': 50000, 'prop-email': 'contact@acme.com', 'prop-phone': '+1-555-0100', 'prop-last-contact': d(-2), 'prop-vip': true, 'prop-source': 'src-ref' }, content: [], createdAt: d(-30), updatedAt: d(-2), createdBy: 'Alice', lastEditedBy: 'Alice' },
  'c2': { id: 'c2', databaseId: DB_CRM, icon: '🌐', properties: { 'prop-name': 'Globex Industries', 'prop-company': 'Globex Corp', 'prop-stage': 'crm-lead', 'prop-value': 120000, 'prop-email': 'sales@globex.com', 'prop-phone': '+1-555-0200', 'prop-last-contact': d(-1), 'prop-vip': false, 'prop-source': 'src-web' }, content: [], createdAt: d(-14), updatedAt: d(-1), createdBy: 'Bob', lastEditedBy: 'Bob' },
  'c3': { id: 'c3', databaseId: DB_CRM, properties: { 'prop-name': 'Initech Systems', 'prop-company': 'Initech LLC', 'prop-stage': 'crm-proposal', 'prop-value': 15000, 'prop-email': 'info@initech.com', 'prop-phone': '+1-555-0300', 'prop-last-contact': d(-5), 'prop-vip': false, 'prop-source': 'src-cold' }, content: [], createdAt: d(-20), updatedAt: d(-5), createdBy: 'Charlie', lastEditedBy: 'Charlie' },
  'c4': { id: 'c4', databaseId: DB_CRM, properties: { 'prop-name': 'Soylent Corp', 'prop-company': 'Soylent Corp', 'prop-stage': 'crm-lost', 'prop-value': 80000, 'prop-email': 'hello@soylent.com', 'prop-phone': '+1-555-0400', 'prop-last-contact': d(-40), 'prop-vip': false, 'prop-source': 'src-ref' }, content: [], createdAt: d(-60), updatedAt: d(-40), createdBy: 'Alice', lastEditedBy: 'Alice' },
  'c5': { id: 'c5', databaseId: DB_CRM, icon: '⭐', properties: { 'prop-name': 'Umbrella Corp', 'prop-company': 'Umbrella Corp', 'prop-stage': 'crm-negotiation', 'prop-value': 250000, 'prop-email': 'deals@umbrella.com', 'prop-phone': '+1-555-0500', 'prop-last-contact': d(0), 'prop-vip': true, 'prop-source': 'src-web' }, content: [], createdAt: d(-7), updatedAt: now, createdBy: 'Bob', lastEditedBy: 'Bob' },
  'c6': { id: 'c6', databaseId: DB_CRM, properties: { 'prop-name': 'Cyberdyne Tech', 'prop-company': 'Cyberdyne', 'prop-stage': 'crm-qualified', 'prop-value': 45000, 'prop-email': 'sales@cyberdyne.io', 'prop-last-contact': d(-3), 'prop-vip': false, 'prop-source': 'src-web' }, content: [], createdAt: d(-10), updatedAt: d(-3), createdBy: 'Diana', lastEditedBy: 'Diana' },
  // — Content —
  'ct1': { id: 'ct1', databaseId: DB_CONTENT, icon: '✍️', properties: { 'prop-title': '10 Tips for React Performance', 'prop-platform': ['plat-tw', 'plat-li'], 'prop-status': 'con-pub', 'prop-date': d(-8), 'prop-author': 'Alice', 'prop-approved': true, 'prop-url': 'https://blog.example.com/react-tips' }, content: [{ id: 'b3', type: 'paragraph', content: 'React performance optimization guide covering memoization, virtualization, and code splitting strategies.' }], createdAt: d(-15), updatedAt: d(-8), createdBy: 'Alice', lastEditedBy: 'Alice' },
  'ct2': { id: 'ct2', databaseId: DB_CONTENT, properties: { 'prop-title': 'State Management in 2026', 'prop-platform': ['plat-blog'], 'prop-status': 'con-draft', 'prop-date': d(3), 'prop-author': 'Bob', 'prop-approved': false }, content: [], createdAt: d(-5), updatedAt: d(-1), createdBy: 'Bob', lastEditedBy: 'Bob' },
  'ct3': { id: 'ct3', databaseId: DB_CONTENT, properties: { 'prop-title': 'Vite vs Webpack Deep Dive', 'prop-platform': ['plat-yt'], 'prop-status': 'con-idea', 'prop-date': d(15), 'prop-author': 'Charlie', 'prop-approved': false }, content: [], createdAt: d(-2), updatedAt: d(-2), createdBy: 'Charlie', lastEditedBy: 'Charlie' },
  'ct4': { id: 'ct4', databaseId: DB_CONTENT, icon: '📧', properties: { 'prop-title': 'Monthly Product Update', 'prop-platform': ['plat-news'], 'prop-status': 'con-review', 'prop-date': d(1), 'prop-author': 'Diana', 'prop-approved': false }, content: [], createdAt: d(-3), updatedAt: now, createdBy: 'Diana', lastEditedBy: 'Diana' },
  'ct5': { id: 'ct5', databaseId: DB_CONTENT, properties: { 'prop-title': 'TypeScript 6.0 First Look', 'prop-platform': ['plat-blog', 'plat-tw'], 'prop-status': 'con-scheduled', 'prop-date': d(5), 'prop-author': 'Alice', 'prop-approved': true }, content: [], createdAt: d(-1), updatedAt: d(-1), createdBy: 'Alice', lastEditedBy: 'Alice' },
  // — Inventory —
  'i1': { id: 'i1', databaseId: DB_INVENTORY, icon: '💻', properties: { 'prop-name': 'MacBook Pro M3', 'prop-category': 'cat-hw', 'prop-serial': 'C02X12345', 'prop-price': 2499, 'prop-purchase': d(-90), 'prop-active': true, 'prop-location': { address: 'Office A — Building 1, Floor 2' }, 'prop-inv-id': 'INV-1' }, content: [], createdAt: d(-90), updatedAt: d(-90), createdBy: 'Alice', lastEditedBy: 'Alice' },
  'i2': { id: 'i2', databaseId: DB_INVENTORY, icon: '🎨', properties: { 'prop-name': 'Figma Enterprise', 'prop-category': 'cat-sw', 'prop-serial': 'LIC-998877', 'prop-price': 540, 'prop-purchase': d(-60), 'prop-active': true, 'prop-location': { address: 'Cloud' }, 'prop-inv-id': 'INV-2' }, content: [], createdAt: d(-60), updatedAt: d(-60), createdBy: 'Alice', lastEditedBy: 'Alice' },
  'i3': { id: 'i3', databaseId: DB_INVENTORY, icon: '🪑', properties: { 'prop-name': 'Herman Miller Aeron', 'prop-category': 'cat-furn', 'prop-serial': 'HM-445566', 'prop-price': 1200, 'prop-purchase': d(-200), 'prop-active': true, 'prop-location': { address: 'Office B — Building 2, Floor 1' }, 'prop-inv-id': 'INV-3' }, content: [], createdAt: d(-200), updatedAt: d(-200), createdBy: 'Bob', lastEditedBy: 'Bob' },
  'i4': { id: 'i4', databaseId: DB_INVENTORY, icon: '🖥️', properties: { 'prop-name': 'Dell UltraSharp 32"', 'prop-category': 'cat-hw', 'prop-serial': 'DL-112233', 'prop-price': 899, 'prop-purchase': d(-120), 'prop-active': true, 'prop-location': { address: 'Office A — Building 1, Floor 2' }, 'prop-inv-id': 'INV-4' }, content: [], createdAt: d(-120), updatedAt: d(-120), createdBy: 'Charlie', lastEditedBy: 'Charlie' },
  'i5': { id: 'i5', databaseId: DB_INVENTORY, properties: { 'prop-name': 'Standing Desk Frame', 'prop-category': 'cat-furn', 'prop-serial': 'SD-778899', 'prop-price': 450, 'prop-purchase': d(-180), 'prop-active': false, 'prop-location': { address: 'Storage B-3' }, 'prop-inv-id': 'INV-5' }, content: [], createdAt: d(-180), updatedAt: d(-30), createdBy: 'Diana', lastEditedBy: 'Diana' },
};

export const coreViews: Record<string, ViewConfig> = {
  'v-tasks-table': { id: 'v-tasks-table', databaseId: DB_TASKS, name: 'All Tasks', type: 'table', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-title', 'prop-status', 'prop-priority', 'prop-tags', 'prop-assignee', 'prop-due', 'prop-done', 'prop-points', 'prop-project'], settings: { showVerticalLines: true } },
  'v-tasks-board': { id: 'v-tasks-board', databaseId: DB_TASKS, name: 'Board', type: 'board', filters: [], filterConjunction: 'and', sorts: [], grouping: { propertyId: 'prop-status' }, visibleProperties: ['prop-title', 'prop-priority', 'prop-tags', 'prop-assignee', 'prop-due', 'prop-points'], settings: { colorColumns: true, cardSize: 'medium' } },
  'v-tasks-timeline': { id: 'v-tasks-timeline', databaseId: DB_TASKS, name: 'Timeline', type: 'timeline', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-title', 'prop-status', 'prop-assignee'], settings: { showTable: true, zoomLevel: 'week' } },
  'v-tasks-list': { id: 'v-tasks-list', databaseId: DB_TASKS, name: 'List', type: 'list', filters: [], filterConjunction: 'and', sorts: [], grouping: { propertyId: 'prop-status' }, visibleProperties: ['prop-title', 'prop-status', 'prop-priority', 'prop-assignee', 'prop-due'], settings: { showPageIcon: true } },
  'v-crm-table': { id: 'v-crm-table', databaseId: DB_CRM, name: 'All Contacts', type: 'table', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-name', 'prop-company', 'prop-stage', 'prop-value', 'prop-email', 'prop-phone', 'prop-last-contact', 'prop-vip', 'prop-source', 'prop-projects'], settings: { showVerticalLines: true } },
  'v-crm-board': { id: 'v-crm-board', databaseId: DB_CRM, name: 'Pipeline', type: 'board', filters: [], filterConjunction: 'and', sorts: [], grouping: { propertyId: 'prop-stage' }, visibleProperties: ['prop-name', 'prop-company', 'prop-value', 'prop-vip'], settings: { colorColumns: true, cardSize: 'medium' } },
  'v-crm-gallery': { id: 'v-crm-gallery', databaseId: DB_CRM, name: 'Gallery', type: 'gallery', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-name', 'prop-company', 'prop-stage', 'prop-value'], settings: { cardSize: 'medium', cardPreview: 'none' } },
  'v-content-calendar': { id: 'v-content-calendar', databaseId: DB_CONTENT, name: 'Calendar', type: 'calendar', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-title', 'prop-status', 'prop-platform'], settings: { showWeekends: true, showCalendarAs: 'month' } },
  'v-content-table': { id: 'v-content-table', databaseId: DB_CONTENT, name: 'Table', type: 'table', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-title', 'prop-platform', 'prop-status', 'prop-date', 'prop-author', 'prop-approved'], settings: { showVerticalLines: true } },
  'v-content-board': { id: 'v-content-board', databaseId: DB_CONTENT, name: 'Board', type: 'board', filters: [], filterConjunction: 'and', sorts: [], grouping: { propertyId: 'prop-status' }, visibleProperties: ['prop-title', 'prop-platform', 'prop-date', 'prop-author'], settings: { colorColumns: true } },
  'v-inv-table': { id: 'v-inv-table', databaseId: DB_INVENTORY, name: 'Assets', type: 'table', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-name', 'prop-category', 'prop-serial', 'prop-price', 'prop-purchase', 'prop-active', 'prop-location'], settings: { showVerticalLines: true } },
  'v-inv-gallery': { id: 'v-inv-gallery', databaseId: DB_INVENTORY, name: 'Gallery', type: 'gallery', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-name', 'prop-category', 'prop-price', 'prop-active'], settings: { cardSize: 'medium', cardPreview: 'none' } },
  'v-inv-chart': { id: 'v-inv-chart', databaseId: DB_INVENTORY, name: 'Chart', type: 'chart', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-name', 'prop-category', 'prop-price'], settings: { chartType: 'vertical_bar', xAxisProperty: 'prop-category', yAxisProperty: 'prop-price', yAxisAggregation: 'sum' } },
  'v-inv-dashboard': { id: 'v-inv-dashboard', databaseId: DB_INVENTORY, name: 'Dashboard', type: 'dashboard', filters: [], filterConjunction: 'and', sorts: [], visibleProperties: ['prop-name', 'prop-category', 'prop-price', 'prop-active'], settings: {} },
};
